---
galaxy_info:
  role_name: java-open-jdk11
  author: Sreyas
  description: "Ansible role for configuring Open JDK Java 11 or Server JRE with local installation support"
  license: TCS
  min_ansible_version: 1.9

  galaxy_tags:
    - development
    - system
    - java
    - jdk
    - openjdk

  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
    - name: EL
      versions:
        - 6
        - 7

dependencies: []
