---
- name: "Check if app has started invoking {{ item }}"
  uri:
    url: "{{ item }}"
    return_content: yes
    status_code: "200"
  register: result
  until: result.status == 200
  retries: "{{ sb_app_healthcheck_retry_count }}"
  delay: "{{ sb_app_healthcheck_retry_delay }}"
  
- name: "Print {{ item }} response"
  debug:
    msg: "{{ result.content }}"
