---
# defaults file for sb-ansible-role

sb_user: vagrant
sb_group: vagrant
sb_app_group_id: sreyas.test
sb_app_artifact_id: sld-master
sb_app_version: 0.0.1-SNAPSHOT
sb_app_maven_repo: https://maven-repository/repository/releases
sb_app_maven_user: maven-user
sb_app_maven_password: maven-password
sb_application_dir: /opt/sld

sb_app_java_version: 11.0.10
sb_app_java_base_dir: '/usr/lib/jre-{{ sb_app_java_version }}'
sb_app_java_remote_repo: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jre_x64_linux_hotspot_11.0.10_9.tar.gz'
sb_app_install_java: false
sb_create_user_group: false


sb_app_healthcheck_retry_count: 10
sb_app_healthcheck_retry_delay: 6

sb_app_extension: jar

sb_app_java_opts_xms: 256M
sb_app_java_opts_xmx: 1024M

sb_application_conf_dir: '{{ sb_application_dir }}/config'
sb_application_logs_dir: '{{ sb_application_dir }}/logs'

sb_config_file_path: '{{ sb_application_conf_dir }}/sld-application.properties'

sb_configuration_files: [{ src: 'sld.app.properties.j2', dest: '{{ sb_config_file_path }}' }]

sb_app_maven_download: false
sb_app_maven_local_download: false
sb_app_local_present: true
sb_app_folder: /etc/ansible/jar

sb_app_env: []

sb_app_service_name: '{{sb_app_artifact_id}}'
